### ISSUE TITLE
Missed sign up widget in the develop branch

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-webapp#613]
If you use the configuration below you have no ability to switch on sign up form/widget

```
defaultLayout:
    - class: row
      content:
        - class: 'col-sm-6 col-sm-offset-3 m-auto'
          widget:
              selector: 'xm-widget-sign-in-up'
              config:
                  signUpEnabled: true
```
**MASTER:**
![login-master](https://user-images.githubusercontent.com/25796355/89335936-5ad1d080-d6a1-11ea-9663-d0f8ff136c9f.png)

**DEVELOP:**
![login-develop](https://user-images.githubusercontent.com/25796355/89335987-6cb37380-d6a1-11ea-87dd-f0ce69b7959b.png)

Please look into this and fix it.
